name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to your preferred version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Build Application
        run: npm run build

  # Uncomment and configure this job if you want to add a deployment step.test
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #
  #     - name: Install Dependencies
  #       run: npm install
  #
  #     - name: Build Application
  #       run: npm run build
  #
  #     - name: Deploy to <Your Deployment Platform>
  #       run: |
  #         # Insert your deployment script here.
  #         echo "Deploying application..."